### ISSUE TITLE
issue1: Unable to register

### ISSUE THREAD

**Issue by AliAhsan69** [RohmaAr/SQE#1]
The application does not allow new user to register when cliked on "Register here" on the Login Page
Steps To generate the Isuue:
1. Execute the program
2. Click on "Register here" link on login page
3. Enter the credentials
4. Click on "Register button"
5. You will get a "whitelabel error page"

if you run the code for the 1st time, this error will generate, of you do this the second time same error will come, but on the third try the user is being successfully registered. As there have already been two saved users in the database and their ids are 1 and 2 respectively whe the code is executed for the 1st time and you regester 1st user the program generates the next id as 1 which causes the error for the first two users registration

**Comment by usmanf07** [comment]
Screenshots could have been helpful. Improper bug reporting format

**Comment by AliAhsan69** [comment]
Thanks for the feedback
I just want confirm, is it improper format due to only the screenshot or
the rest format is wrong aswell?

**Comment by usmanf07** [comment]
Screenshots are a must in reporting bugs. Moreover, in the above report, only the steps part is valid.
Formally, the following are required in bug reporting format:

- Title: Provide a concise yet descriptive title for the bug report.
- Environment: Detail the environment in which the bug occurred. Example system/windows version, the device being used
- Steps to Reproduce
- Expected/Actual Behavior
- Screenshots/Logs/Errors in Console/Exceptions/Error Codes
- If there is any Additional Information, mention it very briefly and to the point under the heading of "Additional Information"
- Also prefer to use a numeric based issue ID instead of "issue1" for example #1813246

Also you can provide any other information that might be relevant or helpful in resolving the bug

**Comment by AliAhsan69** [comment]
Once again thanks for the feedback, can you please review the document for
the deliverable 2 that I have uploaded on the classroom. In that there are
more detailed analysis of each issue, gap analysis aswell, as well as more
detailed exection steps

**Comment by usmanf07** [comment]
Test Case Design & Bug Reporting are two different things. Even test case execution is not similar to bug reporting. You have been given marks for the document. The bug reporting had separate marks. In your deliverable you are required to report issues/bugs on github, not in document. Same will be followed if you will be working in a company in future.

Test Cases are Designed in Documents
Issues are reported on github

**Comment by AliAhsan69** [comment]
Registration issue has been removed successfully. 
Before issue:
1.Go to http://localhost:8080/register
2.Enter your info
3.Click register
4.Generates a whitelabel error
![Screenshot 2023-11-30 001514](https://github.com/RohmaAr/SQE/assets/102369293/0fc5062a-8dda-4a33-849a-1ed33cad6d54)
![Screenshot 2023-11-30 001541](https://github.com/RohmaAr/SQE/assets/102369293/c939aa29-2d08-4ba6-91aa-69c16ebc3e3c)
Afrer solving:
1.Go to http://localhost:8080/register
2.Enter your info
3.Click register
4.Generates the login page where you can enter the new credentials and login to the website
![Screenshot 2023-11-30 002109](https://github.com/RohmaAr/SQE/assets/102369293/6dec9196-ca77-4212-9c46-f8cd0ba04053)
![Screenshot 2023-11-30 002124](https://github.com/RohmaAr/SQE/assets/102369293/a6f7fd73-f418-4e67-bd02-2c9fbd17e5e0)
